services:
  app_proxy:
    environment:
      APP_HOST: mitr4-public-pool-ui_web_1
      APP_PORT: 80   # Porta interna do container (a UI serve em 80 normalmente)

  web:
    image: ghcr.io/mitrajunior/public-poolui-mitr4-custom:latest
    restart: on-failure
    stop_grace_period: 1m
    environment:
      TZ: Europe/Lisbon
      LOGLEVEL: INFO
      LOGFORMAT: json
      # Se o teu frontend precisa de apontar para o backend:
      # PUBLIC_POOL_API_URL: "http://<ip-do-backend>:<porta>"
